### PR TITLE
add payload to PaymentRequest model. upgrade dependencies.

### PR DESCRIPTION
**Pull request by mohammadestk**
add payload to PaymentRequest model. upgrade dependencies.

### CODE REVIEW

**Comment by ImanX** [comment]
Hey @mohammadestk Thanks for open PL in.
I reviewed your commit and change, I faced to `Payload` 
can you describe about it to me?

**Comment by mohammadestk** [comment]
Thank you for your review. In-app purchases can have different types. For example, in a program I am developing, there are two special types of monthly subscriptions and packages. When returning from the purchase, the options are activated depending on the type of purchased package (special or subscription). This requires a field to detect this. I currently use the description field. But the usage of this field is different

**Comment by ImanX** [comment]
Your opinion is wonderful, but in my comment it's better `Payload` handle as query string in `CallbackURL`
Can you attach `Payload` in `CallbackURL` and get it when callback from PG?

**Comment by mohammadestk** [comment]
Thanks for the guidance. Yes, I have to use CallbackURL instead of the description. Because using CallbackURL requires string processing, I think Payload with object oriented is simpler.

**Comment by ImanX** [comment]
OK
So You attach Payload to CallbackURL by a key as query string and open PL again.
Thanks a lot.

**Pull request closed without merging**
